=== kaustubhz/Advanced-web-programming/Section-9/XMLProject/bin/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT student (prn,name,course,address)>
<!ELEMENT prn (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT address (houseNo,street,city,pincode)>
<!ELEMENT houseNo (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT pincode (#PCDATA)>

=== kaustubhz/Advanced-web-programming/Section-9/XMLProject/src/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "test.dtd" >
<student>
  <prn>prn</prn>
  <name>name</name>
  <course>course</course>
  <address>
    <houseNo>houseNo</houseNo>
    <street>street</street>
    <city>city</city>
    <pincode>pincode</pincode>
  </address>
</student>
